import Head from "next/head";
import {
  Heading,
  Box,
  Text,
  VStack,
  SimpleGrid,
  Image,
  Button,
} from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import { imageTake } from "./../constants/imageTake";
import Textt from "../components/Textt";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <VStack mt={5} align="center">
          <Box mb="20px" align="center">
            <Heading>Our Top Menu</Heading>
            <Textt
              title="Sample text. Click to select the text box. Click again or double
              click to start editing the text."
            />
            <Button mt={5} colorScheme="teal" variant="outline">
              View More
            </Button>
          </Box>

          <SimpleGrid
            spacing={{ base: 8, md: 10 }}
            columns={{ base: 1, lg: 3 }}
          >
            {imageTake.map((e, index) => {
              return (
                <div key={index}>
                  <Box align="center">
                    <Image
                      h="150px"
                      w="150px"
                      rounded="250px"
                      alt={e.alt}
                      src={e.image}
                    ></Image>
                    <Box align="center" w="250px">
                      <Textt title={e.text} color="gray.500" />
                      <Textt title={"$" + e.price} fontWeight="bold" />
                    </Box>
                  </Box>
                </div>
              );
            })}
          </SimpleGrid>
        </VStack>
      </main>
    </div>
  );
}
